# Generated by Django 4.2.29 on 2026-03-05 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c93c8023-e0f6-480c-9eab-383143c19f39'), editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.IntegerField()),
                ('status', models.CharField(max_length=9, verbose_name=((0, 'pending'), (1, 'analyzing'), (2, 'complete'), (3, 'error')))),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4fc3893c-e8bc-4782-a2cf-200ad19e82ef'), editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
                ('severity', models.CharField(max_length=8, verbose_name=((0, 'bug'), (1, 'security'), (2, 'style'), (3, 'perf')))),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('suggestion', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=9, verbose_name=((0, 'pending'), (1, 'approved'), (2, 'dismissed')))),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DraftComment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7ecda0a1-42b5-4908-84d6-109cae61d7d9'), editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=255)),
                ('posted', models.BooleanField()),
                ('github_comment_id', models.CharField(max_length=255)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.issue')),
            ],
        ),
    ]
