# Generated by Django 4.2.29 on 2026-03-08 21:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('error', 'Error')], max_length=9)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
                ('severity', models.CharField(choices=[('bug', 'Bug'), ('security', 'Security'), ('style', 'Style'), ('perf', 'Performance')], max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('suggestion', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], max_length=9)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DraftComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=255)),
                ('posted', models.BooleanField()),
                ('github_comment_id', models.CharField(max_length=255)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.issue')),
            ],
        ),
    ]
