# Generated by Django 4.2.29 on 2026-03-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcomment',
            name='github_comment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='draftcomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.issue'),
        ),
        migrations.AlterField(
            model_name='draftcomment',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reviews.pullrequest'),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
