# Generated by Django 4.2.29 on 2026-03-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_draftcomment_github_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='review_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='draftcomment',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='suggestion',
            field=models.TextField(),
        ),
    ]
