# Generated by Django 4.2.29 on 2026-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_pullrequest_error_message_pullrequest_review_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='repo',
            field=models.CharField(default='', help_text='GitHub repo in owner/name format, e.g. django/django', max_length=255),
        ),
    ]
